/**
 * Room Booking API
 * REST API для управления переговорными комнатами и бронированием.  ## Возможности - Управление переговорными комнатами (CRUD) - Бронирование временных слотов - Проверка доступности комнат - Подтверждение и отмена бронирований  ## Статусы бронирования - **PENDING** — Ожидает подтверждения - **CONFIRMED** — Подтверждено - **CANCELLED** — Отменено - **EXPIRED** — Истекло (время прошло) 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: booking-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RoomBookingApi);
  }
}(this, function(expect, RoomBookingApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RoomBookingApi.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('cancelBooking', function() {
      it('should call cancelBooking successfully', function(done) {
        //uncomment below and update the code to test cancelBooking
        //instance.cancelBooking(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('checkAvailable', function() {
      it('should call checkAvailable successfully', function(done) {
        //uncomment below and update the code to test checkAvailable
        //instance.checkAvailable(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('checkAvailable_0', function() {
      it('should call checkAvailable_0 successfully', function(done) {
        //uncomment below and update the code to test checkAvailable_0
        //instance.checkAvailable_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('confirmBooking', function() {
      it('should call confirmBooking successfully', function(done) {
        //uncomment below and update the code to test confirmBooking
        //instance.confirmBooking(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('countActiveBookings', function() {
      it('should call countActiveBookings successfully', function(done) {
        //uncomment below and update the code to test countActiveBookings
        //instance.countActiveBookings(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createBooking', function() {
      it('should call createBooking successfully', function(done) {
        //uncomment below and update the code to test createBooking
        //instance.createBooking(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createRoom', function() {
      it('should call createRoom successfully', function(done) {
        //uncomment below and update the code to test createRoom
        //instance.createRoom(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deactivateRoom', function() {
      it('should call deactivateRoom successfully', function(done) {
        //uncomment below and update the code to test deactivateRoom
        //instance.deactivateRoom(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getActiveBookingsByRoom', function() {
      it('should call getActiveBookingsByRoom successfully', function(done) {
        //uncomment below and update the code to test getActiveBookingsByRoom
        //instance.getActiveBookingsByRoom(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllRooms', function() {
      it('should call getAllRooms successfully', function(done) {
        //uncomment below and update the code to test getAllRooms
        //instance.getAllRooms(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBookingById', function() {
      it('should call getBookingById successfully', function(done) {
        //uncomment below and update the code to test getBookingById
        //instance.getBookingById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBookingsByOrganizer', function() {
      it('should call getBookingsByOrganizer successfully', function(done) {
        //uncomment below and update the code to test getBookingsByOrganizer
        //instance.getBookingsByOrganizer(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBookingsByRoomAndTimeRange', function() {
      it('should call getBookingsByRoomAndTimeRange successfully', function(done) {
        //uncomment below and update the code to test getBookingsByRoomAndTimeRange
        //instance.getBookingsByRoomAndTimeRange(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBookingsByStatus', function() {
      it('should call getBookingsByStatus successfully', function(done) {
        //uncomment below and update the code to test getBookingsByStatus
        //instance.getBookingsByStatus(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getRoomById', function() {
      it('should call getRoomById successfully', function(done) {
        //uncomment below and update the code to test getRoomById
        //instance.getRoomById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateBooking', function() {
      it('should call updateBooking successfully', function(done) {
        //uncomment below and update the code to test updateBooking
        //instance.updateBooking(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateRoom', function() {
      it('should call updateRoom successfully', function(done) {
        //uncomment below and update the code to test updateRoom
        //instance.updateRoom(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
