/**
 * Room Booking API
 * REST API для управления переговорными комнатами и бронированием.  ## Возможности - Управление переговорными комнатами (CRUD) - Бронирование временных слотов - Проверка доступности комнат - Подтверждение и отмена бронирований  ## Статусы бронирования - **PENDING** — Ожидает подтверждения - **CONFIRMED** — Подтверждено - **CANCELLED** — Отменено - **EXPIRED** — Истекло (время прошло) 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: booking-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RoomBookingApi);
  }
}(this, function(expect, RoomBookingApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RoomBookingApi.AvailabilityResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AvailabilityResponse', function() {
    it('should create an instance of AvailabilityResponse', function() {
      // uncomment below and update the code to test AvailabilityResponse
      //var instance = new RoomBookingApi.AvailabilityResponse();
      //expect(instance).to.be.a(RoomBookingApi.AvailabilityResponse);
    });

    it('should have the property available (base name: "available")', function() {
      // uncomment below and update the code to test the property available
      //var instance = new RoomBookingApi.AvailabilityResponse();
      //expect(instance).to.be();
    });

    it('should have the property conflicts (base name: "conflicts")', function() {
      // uncomment below and update the code to test the property conflicts
      //var instance = new RoomBookingApi.AvailabilityResponse();
      //expect(instance).to.be();
    });

  });

}));
