/**
 * Room Booking API
 * REST API для управления переговорными комнатами и бронированием.  ## Возможности - Управление переговорными комнатами (CRUD) - Бронирование временных слотов - Проверка доступности комнат - Подтверждение и отмена бронирований  ## Статусы бронирования - **PENDING** — Ожидает подтверждения - **CONFIRMED** — Подтверждено - **CANCELLED** — Отменено - **EXPIRED** — Истекло (время прошло) 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: booking-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RoomBookingApi);
  }
}(this, function(expect, RoomBookingApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RoomBookingApi.BookingResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BookingResponse', function() {
    it('should create an instance of BookingResponse', function() {
      // uncomment below and update the code to test BookingResponse
      //var instance = new RoomBookingApi.BookingResponse();
      //expect(instance).to.be.a(RoomBookingApi.BookingResponse);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new RoomBookingApi.BookingResponse();
      //expect(instance).to.be();
    });

    it('should have the property roomId (base name: "roomId")', function() {
      // uncomment below and update the code to test the property roomId
      //var instance = new RoomBookingApi.BookingResponse();
      //expect(instance).to.be();
    });

    it('should have the property roomName (base name: "roomName")', function() {
      // uncomment below and update the code to test the property roomName
      //var instance = new RoomBookingApi.BookingResponse();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new RoomBookingApi.BookingResponse();
      //expect(instance).to.be();
    });

    it('should have the property organizerEmail (base name: "organizerEmail")', function() {
      // uncomment below and update the code to test the property organizerEmail
      //var instance = new RoomBookingApi.BookingResponse();
      //expect(instance).to.be();
    });

    it('should have the property startTime (base name: "startTime")', function() {
      // uncomment below and update the code to test the property startTime
      //var instance = new RoomBookingApi.BookingResponse();
      //expect(instance).to.be();
    });

    it('should have the property endTime (base name: "endTime")', function() {
      // uncomment below and update the code to test the property endTime
      //var instance = new RoomBookingApi.BookingResponse();
      //expect(instance).to.be();
    });

    it('should have the property durationMinutes (base name: "durationMinutes")', function() {
      // uncomment below and update the code to test the property durationMinutes
      //var instance = new RoomBookingApi.BookingResponse();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new RoomBookingApi.BookingResponse();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new RoomBookingApi.BookingResponse();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updatedAt")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new RoomBookingApi.BookingResponse();
      //expect(instance).to.be();
    });

  });

}));
