/**
 * Room Booking API
 * REST API для управления переговорными комнатами и бронированием.  ## Возможности - Управление переговорными комнатами (CRUD) - Бронирование временных слотов - Проверка доступности комнат - Подтверждение и отмена бронирований  ## Статусы бронирования - **PENDING** — Ожидает подтверждения - **CONFIRMED** — Подтверждено - **CANCELLED** — Отменено - **EXPIRED** — Истекло (время прошло) 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: booking-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AvailabilityResponse from '../model/AvailabilityResponse';
import BookingResponse from '../model/BookingResponse';
import BookingStatus from '../model/BookingStatus';
import CreateBookingRequest from '../model/CreateBookingRequest';
import CreateRoomRequest from '../model/CreateRoomRequest';
import ErrorResponse from '../model/ErrorResponse';
import RoomResponse from '../model/RoomResponse';
import UpdateBookingRequest from '../model/UpdateBookingRequest';
import UpdateRoomRequest from '../model/UpdateRoomRequest';

/**
*  service.
* @module api/DefaultApi
* @version 1.0.0
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the cancelBooking operation.
     * @callback module:api/DefaultApi~cancelBookingCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BookingResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Отменить бронирование
     * Переводит бронирование в статус CANCELLED. Отменить можно только PENDING или CONFIRMED бронирования
     * @param {Number} id 
     * @param {module:api/DefaultApi~cancelBookingCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/BookingResponse}
     */
    cancelBooking(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling cancelBooking");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = BookingResponse;
      return this.apiClient.callApi(
        '/api/v1/bookings/{id}/cancel', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the checkAvailable operation.
     * @callback module:api/DefaultApi~checkAvailableCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AvailabilityResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Проверка доступности временного слота
     * Возвращает информацию о доступности временного слота для указанной комнаты.
     * @param {Number} roomId ID комнаты
     * @param {Date} startTime Время начала слота (ISO 8601, UTC)
     * @param {Date} endTime Время окончания слота (ISO 8601, UTC)
     * @param {module:api/DefaultApi~checkAvailableCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AvailabilityResponse}
     */
    checkAvailable(roomId, startTime, endTime, callback) {
      let postBody = null;
      // verify the required parameter 'roomId' is set
      if (roomId === undefined || roomId === null) {
        throw new Error("Missing the required parameter 'roomId' when calling checkAvailable");
      }
      // verify the required parameter 'startTime' is set
      if (startTime === undefined || startTime === null) {
        throw new Error("Missing the required parameter 'startTime' when calling checkAvailable");
      }
      // verify the required parameter 'endTime' is set
      if (endTime === undefined || endTime === null) {
        throw new Error("Missing the required parameter 'endTime' when calling checkAvailable");
      }

      let pathParams = {
      };
      let queryParams = {
        'roomId': roomId,
        'startTime': startTime,
        'endTime': endTime
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = AvailabilityResponse;
      return this.apiClient.callApi(
        '/api/v1/bookings/availability', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the checkAvailable_0 operation.
     * @callback module:api/DefaultApi~checkAvailable_0Callback
     * @param {String} error Error message, if any.
     * @param {module:model/AvailabilityResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Проверка доступности временного слота
     * Возвращает информацию о доступности временного слота для указанной комнаты.
     * @param {Number} roomId ID комнаты
     * @param {Date} startTime Время начала слота (ISO 8601, UTC)
     * @param {Date} endTime Время окончания слота (ISO 8601, UTC)
     * @param {module:api/DefaultApi~checkAvailable_0Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AvailabilityResponse}
     */
    checkAvailable_0(roomId, startTime, endTime, callback) {
      let postBody = null;
      // verify the required parameter 'roomId' is set
      if (roomId === undefined || roomId === null) {
        throw new Error("Missing the required parameter 'roomId' when calling checkAvailable_0");
      }
      // verify the required parameter 'startTime' is set
      if (startTime === undefined || startTime === null) {
        throw new Error("Missing the required parameter 'startTime' when calling checkAvailable_0");
      }
      // verify the required parameter 'endTime' is set
      if (endTime === undefined || endTime === null) {
        throw new Error("Missing the required parameter 'endTime' when calling checkAvailable_0");
      }

      let pathParams = {
      };
      let queryParams = {
        'roomId': roomId,
        'startTime': startTime,
        'endTime': endTime
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = AvailabilityResponse;
      return this.apiClient.callApi(
        '/api/v1/bookings/availability', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the confirmBooking operation.
     * @callback module:api/DefaultApi~confirmBookingCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BookingResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Подтвердить бронирование
     * Переводит бронирование из статуса PENDING в CONFIRMED. Только бронирования в статусе PENDING могут быть подтверждены
     * @param {Number} id 
     * @param {module:api/DefaultApi~confirmBookingCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/BookingResponse}
     */
    confirmBooking(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling confirmBooking");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = BookingResponse;
      return this.apiClient.callApi(
        '/api/v1/bookings/{id}/confirm', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the countActiveBookings operation.
     * @callback module:api/DefaultApi~countActiveBookingsCallback
     * @param {String} error Error message, if any.
     * @param {Object.<String, {String: Number}>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Количество активных бронирований комнаты
     * @param {Number} roomId ID комнаты
     * @param {module:api/DefaultApi~countActiveBookingsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object.<String, {String: Number}>}
     */
    countActiveBookings(roomId, callback) {
      let postBody = null;
      // verify the required parameter 'roomId' is set
      if (roomId === undefined || roomId === null) {
        throw new Error("Missing the required parameter 'roomId' when calling countActiveBookings");
      }

      let pathParams = {
        'roomId': roomId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = {'String': 'Number'};
      return this.apiClient.callApi(
        '/api/v1/bookings/room/{roomId}/count', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the createBooking operation.
     * @callback module:api/DefaultApi~createBookingCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BookingResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Создать бронирование
     * @param {module:model/CreateBookingRequest} createBookingRequest 
     * @param {module:api/DefaultApi~createBookingCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/BookingResponse}
     */
    createBooking(createBookingRequest, callback) {
      let postBody = createBookingRequest;
      // verify the required parameter 'createBookingRequest' is set
      if (createBookingRequest === undefined || createBookingRequest === null) {
        throw new Error("Missing the required parameter 'createBookingRequest' when calling createBooking");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = BookingResponse;
      return this.apiClient.callApi(
        '/api/v1/bookings', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the createRoom operation.
     * @callback module:api/DefaultApi~createRoomCallback
     * @param {String} error Error message, if any.
     * @param {module:model/RoomResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Создать переговорную комнату
     * Создаёт новую переговорную комнату с указанным названием, вместимостью и описанием. Комната создаётся в активном состоянии (active = true). 
     * @param {module:model/CreateRoomRequest} createRoomRequest 
     * @param {module:api/DefaultApi~createRoomCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/RoomResponse}
     */
    createRoom(createRoomRequest, callback) {
      let postBody = createRoomRequest;
      // verify the required parameter 'createRoomRequest' is set
      if (createRoomRequest === undefined || createRoomRequest === null) {
        throw new Error("Missing the required parameter 'createRoomRequest' when calling createRoom");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = RoomResponse;
      return this.apiClient.callApi(
        '/api/v1/rooms', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deactivateRoom operation.
     * @callback module:api/DefaultApi~deactivateRoomCallback
     * @param {String} error Error message, if any.
     * @param {module:model/RoomResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Деактивировать комнату
     * Помечает комнату как неактивную (active = false). Деактивированная комната не может быть забронирована. Существующие бронирования **не** отменяются автоматически. 
     * @param {Number} id 
     * @param {module:api/DefaultApi~deactivateRoomCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/RoomResponse}
     */
    deactivateRoom(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deactivateRoom");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = RoomResponse;
      return this.apiClient.callApi(
        '/api/v1/rooms/{id}/deactivate', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getActiveBookingsByRoom operation.
     * @callback module:api/DefaultApi~getActiveBookingsByRoomCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/BookingResponse>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Получить активные бронирования комнаты
     * Возвращает бронирования со статусом PENDING или CONFIRMED
     * @param {Number} roomId 
     * @param {module:api/DefaultApi~getActiveBookingsByRoomCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/BookingResponse>}
     */
    getActiveBookingsByRoom(roomId, callback) {
      let postBody = null;
      // verify the required parameter 'roomId' is set
      if (roomId === undefined || roomId === null) {
        throw new Error("Missing the required parameter 'roomId' when calling getActiveBookingsByRoom");
      }

      let pathParams = {
        'roomId': roomId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [BookingResponse];
      return this.apiClient.callApi(
        '/api/v1/bookings/room/{roomId}/active', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAllRooms operation.
     * @callback module:api/DefaultApi~getAllRoomsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/RoomResponse>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Получить список комнат
     * Возвращает все комнаты или только активные (при activeOnly=true)
     * @param {Object} opts Optional parameters
     * @param {Boolean} [activeOnly = false)] Если true — вернуть только активные комнаты
     * @param {module:api/DefaultApi~getAllRoomsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/RoomResponse>}
     */
    getAllRooms(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'activeOnly': opts['activeOnly']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [RoomResponse];
      return this.apiClient.callApi(
        '/api/v1/rooms', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getBookingById operation.
     * @callback module:api/DefaultApi~getBookingByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BookingResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Получить бронирование по ID
     * @param {Number} id 
     * @param {module:api/DefaultApi~getBookingByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/BookingResponse}
     */
    getBookingById(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getBookingById");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = BookingResponse;
      return this.apiClient.callApi(
        '/api/v1/bookings/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getBookingsByOrganizer operation.
     * @callback module:api/DefaultApi~getBookingsByOrganizerCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/BookingResponse>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Найти бронирования по email организатора
     * @param {String} email Email организатора
     * @param {module:api/DefaultApi~getBookingsByOrganizerCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/BookingResponse>}
     */
    getBookingsByOrganizer(email, callback) {
      let postBody = null;
      // verify the required parameter 'email' is set
      if (email === undefined || email === null) {
        throw new Error("Missing the required parameter 'email' when calling getBookingsByOrganizer");
      }

      let pathParams = {
      };
      let queryParams = {
        'email': email
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [BookingResponse];
      return this.apiClient.callApi(
        '/api/v1/bookings/organizer', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getBookingsByRoomAndTimeRange operation.
     * @callback module:api/DefaultApi~getBookingsByRoomAndTimeRangeCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/BookingResponse>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Получить бронирования комнаты за период
     * Возвращает все бронирования указанной комнаты в заданном временном диапазоне
     * @param {Number} roomId 
     * @param {Date} from Начало диапазона (ISO 8601, UTC)
     * @param {Date} to Конец диапазона (ISO 8601, UTC)
     * @param {module:api/DefaultApi~getBookingsByRoomAndTimeRangeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/BookingResponse>}
     */
    getBookingsByRoomAndTimeRange(roomId, from, to, callback) {
      let postBody = null;
      // verify the required parameter 'roomId' is set
      if (roomId === undefined || roomId === null) {
        throw new Error("Missing the required parameter 'roomId' when calling getBookingsByRoomAndTimeRange");
      }
      // verify the required parameter 'from' is set
      if (from === undefined || from === null) {
        throw new Error("Missing the required parameter 'from' when calling getBookingsByRoomAndTimeRange");
      }
      // verify the required parameter 'to' is set
      if (to === undefined || to === null) {
        throw new Error("Missing the required parameter 'to' when calling getBookingsByRoomAndTimeRange");
      }

      let pathParams = {
        'roomId': roomId
      };
      let queryParams = {
        'from': from,
        'to': to
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [BookingResponse];
      return this.apiClient.callApi(
        '/api/v1/bookings/room/{roomId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getBookingsByStatus operation.
     * @callback module:api/DefaultApi~getBookingsByStatusCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/BookingResponse>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Получить бронирования по статусу
     * @param {module:model/BookingStatus} status Статус бронирования для фильтрации
     * @param {module:api/DefaultApi~getBookingsByStatusCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/BookingResponse>}
     */
    getBookingsByStatus(status, callback) {
      let postBody = null;
      // verify the required parameter 'status' is set
      if (status === undefined || status === null) {
        throw new Error("Missing the required parameter 'status' when calling getBookingsByStatus");
      }

      let pathParams = {
      };
      let queryParams = {
        'status': status
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [BookingResponse];
      return this.apiClient.callApi(
        '/api/v1/bookings/status', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getRoomById operation.
     * @callback module:api/DefaultApi~getRoomByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/RoomResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Получить комнату по ID
     * Возвращает полную информацию о переговорной комнате по её уникальному идентификатору
     * @param {Number} id Уникальный идентификатор комнаты
     * @param {module:api/DefaultApi~getRoomByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/RoomResponse}
     */
    getRoomById(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getRoomById");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = RoomResponse;
      return this.apiClient.callApi(
        '/api/v1/rooms/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateBooking operation.
     * @callback module:api/DefaultApi~updateBookingCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BookingResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Обновить бронирование (частично)
     * Частичное обновление бронирования. Передайте только поля, которые нужно изменить.  **Ограничения:** - Нельзя обновить CANCELLED или EXPIRED бронирование - При изменении времени проверяется отсутствие конфликтов 
     * @param {Number} id 
     * @param {module:model/UpdateBookingRequest} updateBookingRequest 
     * @param {module:api/DefaultApi~updateBookingCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/BookingResponse}
     */
    updateBooking(id, updateBookingRequest, callback) {
      let postBody = updateBookingRequest;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateBooking");
      }
      // verify the required parameter 'updateBookingRequest' is set
      if (updateBookingRequest === undefined || updateBookingRequest === null) {
        throw new Error("Missing the required parameter 'updateBookingRequest' when calling updateBooking");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = BookingResponse;
      return this.apiClient.callApi(
        '/api/v1/bookings/{id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateRoom operation.
     * @callback module:api/DefaultApi~updateRoomCallback
     * @param {String} error Error message, if any.
     * @param {module:model/RoomResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Обновить комнату (частично)
     * Обновляет только переданные поля комнаты. Поля со значением null игнорируются
     * @param {Number} id 
     * @param {module:model/UpdateRoomRequest} updateRoomRequest 
     * @param {module:api/DefaultApi~updateRoomCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/RoomResponse}
     */
    updateRoom(id, updateRoomRequest, callback) {
      let postBody = updateRoomRequest;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateRoom");
      }
      // verify the required parameter 'updateRoomRequest' is set
      if (updateRoomRequest === undefined || updateRoomRequest === null) {
        throw new Error("Missing the required parameter 'updateRoomRequest' when calling updateRoom");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = RoomResponse;
      return this.apiClient.callApi(
        '/api/v1/rooms/{id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
