/**
 * Room Booking API
 * REST API для управления переговорными комнатами и бронированием.  ## Возможности - Управление переговорными комнатами (CRUD) - Бронирование временных слотов - Проверка доступности комнат - Подтверждение и отмена бронирований  ## Статусы бронирования - **PENDING** — Ожидает подтверждения - **CONFIRMED** — Подтверждено - **CANCELLED** — Отменено - **EXPIRED** — Истекло (время прошло) 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: booking-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AvailabilityResponse from './model/AvailabilityResponse';
import BookingResponse from './model/BookingResponse';
import BookingStatus from './model/BookingStatus';
import CreateBookingRequest from './model/CreateBookingRequest';
import CreateRoomRequest from './model/CreateRoomRequest';
import ErrorResponse from './model/ErrorResponse';
import FieldError from './model/FieldError';
import RoomResponse from './model/RoomResponse';
import UpdateBookingRequest from './model/UpdateBookingRequest';
import UpdateRoomRequest from './model/UpdateRoomRequest';
import DefaultApi from './api/DefaultApi';


/**
* REST API для управления переговорными комнатами и бронированием.  ## Возможности - Управление переговорными комнатами (CRUD) - Бронирование временных слотов - Проверка доступности комнат - Подтверждение и отмена бронирований  ## Статусы бронирования - **PENDING** — Ожидает подтверждения - **CONFIRMED** — Подтверждено - **CANCELLED** — Отменено - **EXPIRED** — Истекло (время прошло) .<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var RoomBookingApi = require('index'); // See note below*.
* var xxxSvc = new RoomBookingApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new RoomBookingApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new RoomBookingApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new RoomBookingApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AvailabilityResponse model constructor.
     * @property {module:model/AvailabilityResponse}
     */
    AvailabilityResponse,

    /**
     * The BookingResponse model constructor.
     * @property {module:model/BookingResponse}
     */
    BookingResponse,

    /**
     * The BookingStatus model constructor.
     * @property {module:model/BookingStatus}
     */
    BookingStatus,

    /**
     * The CreateBookingRequest model constructor.
     * @property {module:model/CreateBookingRequest}
     */
    CreateBookingRequest,

    /**
     * The CreateRoomRequest model constructor.
     * @property {module:model/CreateRoomRequest}
     */
    CreateRoomRequest,

    /**
     * The ErrorResponse model constructor.
     * @property {module:model/ErrorResponse}
     */
    ErrorResponse,

    /**
     * The FieldError model constructor.
     * @property {module:model/FieldError}
     */
    FieldError,

    /**
     * The RoomResponse model constructor.
     * @property {module:model/RoomResponse}
     */
    RoomResponse,

    /**
     * The UpdateBookingRequest model constructor.
     * @property {module:model/UpdateBookingRequest}
     */
    UpdateBookingRequest,

    /**
     * The UpdateRoomRequest model constructor.
     * @property {module:model/UpdateRoomRequest}
     */
    UpdateRoomRequest,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
