/**
 * Room Booking API
 * REST API для управления переговорными комнатами и бронированием.  ## Возможности - Управление переговорными комнатами (CRUD) - Бронирование временных слотов - Проверка доступности комнат - Подтверждение и отмена бронирований  ## Статусы бронирования - **PENDING** — Ожидает подтверждения - **CONFIRMED** — Подтверждено - **CANCELLED** — Отменено - **EXPIRED** — Истекло (время прошло) 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: booking-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BookingResponse from './BookingResponse';

/**
 * The AvailabilityResponse model module.
 * @module model/AvailabilityResponse
 * @version 1.0.0
 */
class AvailabilityResponse {
    /**
     * Constructs a new <code>AvailabilityResponse</code>.
     * Результат проверки доступности временного слота
     * @alias module:model/AvailabilityResponse
     */
    constructor() { 
        
        AvailabilityResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AvailabilityResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AvailabilityResponse} obj Optional instance to populate.
     * @return {module:model/AvailabilityResponse} The populated <code>AvailabilityResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AvailabilityResponse();

            if (data.hasOwnProperty('available')) {
                obj['available'] = ApiClient.convertToType(data['available'], 'Boolean');
            }
            if (data.hasOwnProperty('conflicts')) {
                obj['conflicts'] = ApiClient.convertToType(data['conflicts'], [BookingResponse]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AvailabilityResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AvailabilityResponse</code>.
     */
    static validateJSON(data) {
        if (data['conflicts']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['conflicts'])) {
                throw new Error("Expected the field `conflicts` to be an array in the JSON data but got " + data['conflicts']);
            }
            // validate the optional field `conflicts` (array)
            for (const item of data['conflicts']) {
                BookingResponse.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * Доступен ли запрошенный временной слот
 * @member {Boolean} available
 */
AvailabilityResponse.prototype['available'] = undefined;

/**
 * Список конфликтующих бронирований (только если available = false)
 * @member {Array.<module:model/BookingResponse>} conflicts
 */
AvailabilityResponse.prototype['conflicts'] = undefined;






export default AvailabilityResponse;

