/**
 * Room Booking API
 * REST API для управления переговорными комнатами и бронированием.  ## Возможности - Управление переговорными комнатами (CRUD) - Бронирование временных слотов - Проверка доступности комнат - Подтверждение и отмена бронирований  ## Статусы бронирования - **PENDING** — Ожидает подтверждения - **CONFIRMED** — Подтверждено - **CANCELLED** — Отменено - **EXPIRED** — Истекло (время прошло) 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: booking-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BookingStatus from './BookingStatus';

/**
 * The BookingResponse model module.
 * @module model/BookingResponse
 * @version 1.0.0
 */
class BookingResponse {
    /**
     * Constructs a new <code>BookingResponse</code>.
     * Информация о бронировании переговорной комнаты
     * @alias module:model/BookingResponse
     */
    constructor() { 
        
        BookingResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BookingResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BookingResponse} obj Optional instance to populate.
     * @return {module:model/BookingResponse} The populated <code>BookingResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BookingResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('roomId')) {
                obj['roomId'] = ApiClient.convertToType(data['roomId'], 'Number');
            }
            if (data.hasOwnProperty('roomName')) {
                obj['roomName'] = ApiClient.convertToType(data['roomName'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('organizerEmail')) {
                obj['organizerEmail'] = ApiClient.convertToType(data['organizerEmail'], 'String');
            }
            if (data.hasOwnProperty('startTime')) {
                obj['startTime'] = ApiClient.convertToType(data['startTime'], 'Date');
            }
            if (data.hasOwnProperty('endTime')) {
                obj['endTime'] = ApiClient.convertToType(data['endTime'], 'Date');
            }
            if (data.hasOwnProperty('durationMinutes')) {
                obj['durationMinutes'] = ApiClient.convertToType(data['durationMinutes'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], BookingStatus);
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BookingResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BookingResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['roomName'] && !(typeof data['roomName'] === 'string' || data['roomName'] instanceof String)) {
            throw new Error("Expected the field `roomName` to be a primitive type in the JSON string but got " + data['roomName']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['organizerEmail'] && !(typeof data['organizerEmail'] === 'string' || data['organizerEmail'] instanceof String)) {
            throw new Error("Expected the field `organizerEmail` to be a primitive type in the JSON string but got " + data['organizerEmail']);
        }

        return true;
    }


}



/**
 * Уникальный ID бронирования
 * @member {Number} id
 */
BookingResponse.prototype['id'] = undefined;

/**
 * ID забронированной комнаты
 * @member {Number} roomId
 */
BookingResponse.prototype['roomId'] = undefined;

/**
 * Название комнаты
 * @member {String} roomName
 */
BookingResponse.prototype['roomName'] = undefined;

/**
 * Название встречи
 * @member {String} title
 */
BookingResponse.prototype['title'] = undefined;

/**
 * Email организатора
 * @member {String} organizerEmail
 */
BookingResponse.prototype['organizerEmail'] = undefined;

/**
 * Время начала
 * @member {Date} startTime
 */
BookingResponse.prototype['startTime'] = undefined;

/**
 * Время окончания
 * @member {Date} endTime
 */
BookingResponse.prototype['endTime'] = undefined;

/**
 * Продолжительность в минутах (вычисляется автоматически)
 * @member {Number} durationMinutes
 */
BookingResponse.prototype['durationMinutes'] = undefined;

/**
 * Текущий статус бронирования
 * @member {module:model/BookingStatus} status
 */
BookingResponse.prototype['status'] = undefined;

/**
 * Дата создания
 * @member {Date} createdAt
 */
BookingResponse.prototype['createdAt'] = undefined;

/**
 * Дата последнего обновления
 * @member {Date} updatedAt
 */
BookingResponse.prototype['updatedAt'] = undefined;






export default BookingResponse;

