/**
 * Room Booking API
 * REST API для управления переговорными комнатами и бронированием.  ## Возможности - Управление переговорными комнатами (CRUD) - Бронирование временных слотов - Проверка доступности комнат - Подтверждение и отмена бронирований  ## Статусы бронирования - **PENDING** — Ожидает подтверждения - **CONFIRMED** — Подтверждено - **CANCELLED** — Отменено - **EXPIRED** — Истекло (время прошло) 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: booking-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateRoomRequest model module.
 * @module model/CreateRoomRequest
 * @version 1.0.0
 */
class CreateRoomRequest {
    /**
     * Constructs a new <code>CreateRoomRequest</code>.
     * Запрос на создание новой переговорной комнаты
     * @alias module:model/CreateRoomRequest
     * @param name {String} Название комнаты (уникальное)
     * @param capacity {Number} Вместимость комнаты (количество человек)
     */
    constructor(name, capacity) { 
        
        CreateRoomRequest.initialize(this, name, capacity);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, capacity) { 
        obj['name'] = name;
        obj['capacity'] = capacity;
    }

    /**
     * Constructs a <code>CreateRoomRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateRoomRequest} obj Optional instance to populate.
     * @return {module:model/CreateRoomRequest} The populated <code>CreateRoomRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateRoomRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('capacity')) {
                obj['capacity'] = ApiClient.convertToType(data['capacity'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateRoomRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateRoomRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateRoomRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}

CreateRoomRequest.RequiredProperties = ["name", "capacity"];

/**
 * Название комнаты (уникальное)
 * @member {String} name
 */
CreateRoomRequest.prototype['name'] = undefined;

/**
 * Вместимость комнаты (количество человек)
 * @member {Number} capacity
 */
CreateRoomRequest.prototype['capacity'] = undefined;

/**
 * Описание комнаты: оборудование, расположение и т.д.
 * @member {String} description
 */
CreateRoomRequest.prototype['description'] = undefined;






export default CreateRoomRequest;

