/**
 * Room Booking API
 * REST API для управления переговорными комнатами и бронированием.  ## Возможности - Управление переговорными комнатами (CRUD) - Бронирование временных слотов - Проверка доступности комнат - Подтверждение и отмена бронирований  ## Статусы бронирования - **PENDING** — Ожидает подтверждения - **CONFIRMED** — Подтверждено - **CANCELLED** — Отменено - **EXPIRED** — Истекло (время прошло) 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: booking-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateBookingRequest model module.
 * @module model/CreateBookingRequest
 * @version 1.0.0
 */
class CreateBookingRequest {
    /**
     * Constructs a new <code>CreateBookingRequest</code>.
     * Запрос на создание нового бронирования переговорной комнаты
     * @alias module:model/CreateBookingRequest
     * @param roomId {Number} ID переговорной комнаты для бронирования
     * @param title {String} Название встречи / мероприятия
     * @param organizerEmail {String} Email организатора бронирования
     * @param startTime {Date} Время начала бронирования (ISO 8601, UTC). Должно быть в будущем
     * @param endTime {Date} Время окончания бронирования (ISO 8601, UTC). Должно быть после startTime
     */
    constructor(roomId, title, organizerEmail, startTime, endTime) { 
        
        CreateBookingRequest.initialize(this, roomId, title, organizerEmail, startTime, endTime);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, roomId, title, organizerEmail, startTime, endTime) { 
        obj['roomId'] = roomId;
        obj['title'] = title;
        obj['organizerEmail'] = organizerEmail;
        obj['startTime'] = startTime;
        obj['endTime'] = endTime;
    }

    /**
     * Constructs a <code>CreateBookingRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateBookingRequest} obj Optional instance to populate.
     * @return {module:model/CreateBookingRequest} The populated <code>CreateBookingRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateBookingRequest();

            if (data.hasOwnProperty('roomId')) {
                obj['roomId'] = ApiClient.convertToType(data['roomId'], 'Number');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('organizerEmail')) {
                obj['organizerEmail'] = ApiClient.convertToType(data['organizerEmail'], 'String');
            }
            if (data.hasOwnProperty('startTime')) {
                obj['startTime'] = ApiClient.convertToType(data['startTime'], 'Date');
            }
            if (data.hasOwnProperty('endTime')) {
                obj['endTime'] = ApiClient.convertToType(data['endTime'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateBookingRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateBookingRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateBookingRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['organizerEmail'] && !(typeof data['organizerEmail'] === 'string' || data['organizerEmail'] instanceof String)) {
            throw new Error("Expected the field `organizerEmail` to be a primitive type in the JSON string but got " + data['organizerEmail']);
        }

        return true;
    }


}

CreateBookingRequest.RequiredProperties = ["roomId", "title", "organizerEmail", "startTime", "endTime"];

/**
 * ID переговорной комнаты для бронирования
 * @member {Number} roomId
 */
CreateBookingRequest.prototype['roomId'] = undefined;

/**
 * Название встречи / мероприятия
 * @member {String} title
 */
CreateBookingRequest.prototype['title'] = undefined;

/**
 * Email организатора бронирования
 * @member {String} organizerEmail
 */
CreateBookingRequest.prototype['organizerEmail'] = undefined;

/**
 * Время начала бронирования (ISO 8601, UTC). Должно быть в будущем
 * @member {Date} startTime
 */
CreateBookingRequest.prototype['startTime'] = undefined;

/**
 * Время окончания бронирования (ISO 8601, UTC). Должно быть после startTime
 * @member {Date} endTime
 */
CreateBookingRequest.prototype['endTime'] = undefined;






export default CreateBookingRequest;

