/**
 * Room Booking API
 * REST API для управления переговорными комнатами и бронированием.  ## Возможности - Управление переговорными комнатами (CRUD) - Бронирование временных слотов - Проверка доступности комнат - Подтверждение и отмена бронирований  ## Статусы бронирования - **PENDING** — Ожидает подтверждения - **CONFIRMED** — Подтверждено - **CANCELLED** — Отменено - **EXPIRED** — Истекло (время прошло) 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: booking-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FieldError from './FieldError';

/**
 * The ErrorResponse model module.
 * @module model/ErrorResponse
 * @version 1.0.0
 */
class ErrorResponse {
    /**
     * Constructs a new <code>ErrorResponse</code>.
     * Стандартный формат ответа об ошибке API
     * @alias module:model/ErrorResponse
     * @param timeStamp {Date} Временная метка возникновении ошибки (ISO 8601 UTC)
     * @param status {Number} HTTP-код статуса
     * @param message {String} Человекочитаемое сообщение об ошибке
     */
    constructor(timeStamp, status, message) { 
        
        ErrorResponse.initialize(this, timeStamp, status, message);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, timeStamp, status, message) { 
        obj['timeStamp'] = timeStamp;
        obj['status'] = status;
        obj['message'] = message;
    }

    /**
     * Constructs a <code>ErrorResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ErrorResponse} obj Optional instance to populate.
     * @return {module:model/ErrorResponse} The populated <code>ErrorResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ErrorResponse();

            if (data.hasOwnProperty('timeStamp')) {
                obj['timeStamp'] = ApiClient.convertToType(data['timeStamp'], 'Date');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
            if (data.hasOwnProperty('errorCode')) {
                obj['errorCode'] = ApiClient.convertToType(data['errorCode'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
            if (data.hasOwnProperty('fieldErrors')) {
                obj['fieldErrors'] = ApiClient.convertToType(data['fieldErrors'], [FieldError]);
            }
            if (data.hasOwnProperty('details')) {
                obj['details'] = ApiClient.convertToType(data['details'], {'String': Object});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ErrorResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ErrorResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ErrorResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['error'] && !(typeof data['error'] === 'string' || data['error'] instanceof String)) {
            throw new Error("Expected the field `error` to be a primitive type in the JSON string but got " + data['error']);
        }
        // ensure the json data is a string
        if (data['errorCode'] && !(typeof data['errorCode'] === 'string' || data['errorCode'] instanceof String)) {
            throw new Error("Expected the field `errorCode` to be a primitive type in the JSON string but got " + data['errorCode']);
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }
        // ensure the json data is a string
        if (data['path'] && !(typeof data['path'] === 'string' || data['path'] instanceof String)) {
            throw new Error("Expected the field `path` to be a primitive type in the JSON string but got " + data['path']);
        }
        if (data['fieldErrors']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['fieldErrors'])) {
                throw new Error("Expected the field `fieldErrors` to be an array in the JSON data but got " + data['fieldErrors']);
            }
            // validate the optional field `fieldErrors` (array)
            for (const item of data['fieldErrors']) {
                FieldError.validateJSON(item);
            };
        }

        return true;
    }


}

ErrorResponse.RequiredProperties = ["timeStamp", "status", "message"];

/**
 * Временная метка возникновении ошибки (ISO 8601 UTC)
 * @member {Date} timeStamp
 */
ErrorResponse.prototype['timeStamp'] = undefined;

/**
 * HTTP-код статуса
 * @member {Number} status
 */
ErrorResponse.prototype['status'] = undefined;

/**
 * Краткое описание типа ошибки
 * @member {String} error
 */
ErrorResponse.prototype['error'] = undefined;

/**
 * Машиночитаемый код ошибки для обработке на клиенте
 * @member {String} errorCode
 */
ErrorResponse.prototype['errorCode'] = undefined;

/**
 * Человекочитаемое сообщение об ошибке
 * @member {String} message
 */
ErrorResponse.prototype['message'] = undefined;

/**
 * URI запроса, вызывающего ошибку
 * @member {String} path
 */
ErrorResponse.prototype['path'] = undefined;

/**
 * Список ошибок валидации полей (только для 400 Validation failed)
 * @member {Array.<module:model/FieldError>} fieldErrors
 */
ErrorResponse.prototype['fieldErrors'] = undefined;

/**
 * Дополнительные детали ошибки (зависят от контекста)
 * @member {Object.<String, Object>} details
 */
ErrorResponse.prototype['details'] = undefined;






export default ErrorResponse;

