/**
 * Room Booking API
 * REST API для управления переговорными комнатами и бронированием.  ## Возможности - Управление переговорными комнатами (CRUD) - Бронирование временных слотов - Проверка доступности комнат - Подтверждение и отмена бронирований  ## Статусы бронирования - **PENDING** — Ожидает подтверждения - **CONFIRMED** — Подтверждено - **CANCELLED** — Отменено - **EXPIRED** — Истекло (время прошло) 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: booking-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FieldError model module.
 * @module model/FieldError
 * @version 1.0.0
 */
class FieldError {
    /**
     * Constructs a new <code>FieldError</code>.
     * Детали ошибки валидации конкретного поля
     * @alias module:model/FieldError
     */
    constructor() { 
        
        FieldError.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FieldError</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FieldError} obj Optional instance to populate.
     * @return {module:model/FieldError} The populated <code>FieldError</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FieldError();

            if (data.hasOwnProperty('field')) {
                obj['field'] = ApiClient.convertToType(data['field'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('rejectedValue')) {
                obj['rejectedValue'] = ApiClient.convertToType(data['rejectedValue'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FieldError</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FieldError</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['field'] && !(typeof data['field'] === 'string' || data['field'] instanceof String)) {
            throw new Error("Expected the field `field` to be a primitive type in the JSON string but got " + data['field']);
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }

        return true;
    }


}



/**
 * Имя поля с ошибкой
 * @member {String} field
 */
FieldError.prototype['field'] = undefined;

/**
 * Описание ошибки валидации
 * @member {String} message
 */
FieldError.prototype['message'] = undefined;

/**
 * @member {Object} rejectedValue
 */
FieldError.prototype['rejectedValue'] = undefined;






export default FieldError;

