/**
 * Room Booking API
 * REST API для управления переговорными комнатами и бронированием.  ## Возможности - Управление переговорными комнатами (CRUD) - Бронирование временных слотов - Проверка доступности комнат - Подтверждение и отмена бронирований  ## Статусы бронирования - **PENDING** — Ожидает подтверждения - **CONFIRMED** — Подтверждено - **CANCELLED** — Отменено - **EXPIRED** — Истекло (время прошло) 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: booking-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateRoomRequest model module.
 * @module model/UpdateRoomRequest
 * @version 1.0.0
 */
class UpdateRoomRequest {
    /**
     * Constructs a new <code>UpdateRoomRequest</code>.
     * Запрос на частичное обновление комнаты (PATCH). Передайте только изменяемые поля
     * @alias module:model/UpdateRoomRequest
     */
    constructor() { 
        
        UpdateRoomRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateRoomRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateRoomRequest} obj Optional instance to populate.
     * @return {module:model/UpdateRoomRequest} The populated <code>UpdateRoomRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateRoomRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('capacity')) {
                obj['capacity'] = ApiClient.convertToType(data['capacity'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateRoomRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateRoomRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}



/**
 * Новое название комнаты
 * @member {String} name
 */
UpdateRoomRequest.prototype['name'] = undefined;

/**
 * Новая вместимость
 * @member {Number} capacity
 */
UpdateRoomRequest.prototype['capacity'] = undefined;

/**
 * Новое описание комнаты
 * @member {String} description
 */
UpdateRoomRequest.prototype['description'] = undefined;

/**
 * Активна ли комната (false = недоступна для бронирования)
 * @member {Boolean} active
 */
UpdateRoomRequest.prototype['active'] = undefined;






export default UpdateRoomRequest;

