/**
 * Room Booking API
 * REST API для управления переговорными комнатами и бронированием.  ## Возможности - Управление переговорными комнатами (CRUD) - Бронирование временных слотов - Проверка доступности комнат - Подтверждение и отмена бронирований  ## Статусы бронирования - **PENDING** — Ожидает подтверждения - **CONFIRMED** — Подтверждено - **CANCELLED** — Отменено - **EXPIRED** — Истекло (время прошло) 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: booking-team@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateBookingRequest model module.
 * @module model/UpdateBookingRequest
 * @version 1.0.0
 */
class UpdateBookingRequest {
    /**
     * Constructs a new <code>UpdateBookingRequest</code>.
     * Запрос на частичное обновление бронирования (PATCH). Передайте только изменяемые поля
     * @alias module:model/UpdateBookingRequest
     */
    constructor() { 
        
        UpdateBookingRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateBookingRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateBookingRequest} obj Optional instance to populate.
     * @return {module:model/UpdateBookingRequest} The populated <code>UpdateBookingRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateBookingRequest();

            if (data.hasOwnProperty('roomId')) {
                obj['roomId'] = ApiClient.convertToType(data['roomId'], 'Number');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('startTime')) {
                obj['startTime'] = ApiClient.convertToType(data['startTime'], 'Date');
            }
            if (data.hasOwnProperty('endTime')) {
                obj['endTime'] = ApiClient.convertToType(data['endTime'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateBookingRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateBookingRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }

        return true;
    }


}



/**
 * Новый ID комнаты (для переноса в другую комнату)
 * @member {Number} roomId
 */
UpdateBookingRequest.prototype['roomId'] = undefined;

/**
 * Новое название встречи
 * @member {String} title
 */
UpdateBookingRequest.prototype['title'] = undefined;

/**
 * Новое время начала (ISO 8601, UTC)
 * @member {Date} startTime
 */
UpdateBookingRequest.prototype['startTime'] = undefined;

/**
 * Новое время окончания (ISO 8601, UTC)
 * @member {Date} endTime
 */
UpdateBookingRequest.prototype['endTime'] = undefined;






export default UpdateBookingRequest;

